### ISSUE TITLE
Add ability to install this package with Composer using released tags

### ISSUE THREAD

**Issue by bocharsky-bw** [liqpay/sdk-php#10]
Related to the #6

**Comment by sim2github** [comment]
@viplifes 

1. Login with github account https://packagist.org/login/
2. Submit package url https://packagist.org/packages/submit

**Comment by sim2github** [comment]
### Temporrary usage:
composer.json
```json
{
  "require": {
    "liqpay/liqpay": "dev-master"
  },
  "repositories": [
        {
            "type": "git",
            "url": "https://github.com/liqpay/sdk-php.git"
        }
  ],
}
```

**Comment by bocharsky-bw** [comment]
@sim2github thanks! That's exactly what I'm using right now, just want to get rid of specifying repository explicitly and rely on a stable version instead of `dev-master`.

**Comment by viplifes** [comment]
hi.
A package liqpay/liqpay already exists.
https://packagist.org/packages/liqpay/liqpay

**Comment by viplifes** [comment]
speak Russian?

**Comment by bocharsky-bw** [comment]
Да, вы планируете вести [семантическое версионирование](http://semver.org/lang/ru/) этого пакета с помощью Git тегов? Это повысит стабильность проекта к изменениям что позволит разработчикам легче устанавливать пакет и безопастно обновляться к новым версиям

**Comment by sim2github** [comment]
Имеется ввиду что версия должна состоять из 3-х цифр (мажор . минор . патч )
```shell
>git tag -a v1.2.0
>git push --tags
```
https://packagist.org/about#managing-package-versions

**Comment by sim2github** [comment]
`version` в `composer.json` не обязательная и даже не желательна ([Note](https://getcomposer.org/doc/04-schema.md#version))

**Comment by viplifes** [comment]
Спасибо! 
version убрал из composer.json 
Новый тег - https://github.com/liqpay/sdk-php/tree/v1.2.1

**Comment by sim2github** [comment]
Гуд. Работает. Можно закрывать.
```php
  - Installing liqpay/liqpay (v1.2.1)
    Downloading: 100%    
```

**Comment by bocharsky-bw** [comment]
Спасибо
