### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by funivan** [liqpay/sdk-php#6]
Hello. Can you connect `packagist.org` to `github.com`
All new releases will be published in packagist and it will be possible to install specific version of your library.
for example `composer require liqpay/liqpay:1.1`

**Comment by Alehandr0** [comment]
Приветствую, я здесь недавно, особо не пользуюсь этим сервисом. Так что если что-то серьёзное - то я буду вникать, а если это по мелочам, то особого значения это не имеет.
Я так думаю.

**Comment by bocharsky-bw** [comment]
@funivan right, can you add packagist service for this repository in [settings](https://github.com/liqpay/sdk-php/settings/hooks)? Or update this library on [packagist.org](https://packagist.org/packages/liqpay/liqpay), please! I see 2 stable tags on GitHub but not on packagist. I don't want to use **unstable** version in production!

**Comment by bocharsky-bw** [comment]
ping

**Comment by bocharsky-bw** [comment]
@viplifes Could you provide some explanation why you closed it?

**Comment by bocharsky-bw** [comment]
@viplifes thanks for the clear explanation :)
